"""empty message

Revision ID: 5910cd3d7f9e
Revises: 521b5961e504
Create Date: 2020-07-02 13:42:04.864732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5910cd3d7f9e'
down_revision = '521b5961e504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_description', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_description')
    # ### end Alembic commands ###
