"""empty message

Revision ID: 6a5a771f8a88
Revises: de669addedca
Create Date: 2020-07-02 14:17:52.713335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5a771f8a88'
down_revision = 'de669addedca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_description', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
