"""empty message

Revision ID: d44c93e37341
Revises: 5910cd3d7f9e
Create Date: 2020-07-02 13:45:49.094628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44c93e37341'
down_revision = '5910cd3d7f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_description', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
